TITLE_DICT = {
    1: {'name': '創世記', 'link': 'https://www.expecthim.com/genesis-1.html'},
    2: {'name': '出埃及記', 'link': 'https://www.expecthim.com/exodus-1.html'},
    3: {'name': '利未記', 'link': 'https://www.expecthim.com/leviticus-1.html'},
    4: {'name': '民數記', 'link': 'https://www.expecthim.com/numbers-1.html'},
    5: {'name': '申命記', 'link': 'https://www.expecthim.com/deuteronomy-1.html'},
    6: {'name': '約書亞記', 'link': 'https://www.expecthim.com/joshua-1.html'},
    7: {'name': '士師記', 'link': 'https://www.expecthim.com/judges-1.html'},
    8: {'name': '路得記', 'link': 'https://www.expecthim.com/ruth-1.html'},
    9: {'name': '撒母耳記上', 'link': 'https://www.expecthim.com/samuel-1.html'},
    10: {'name': '撒母耳記下', 'link': 'https://www.expecthim.com/2-samuel-1.html'},
    11: {'name': '列王紀上', 'link': 'https://www.expecthim.com/1-kings-1.html'},
    12: {'name': '列王紀下', 'link': 'https://www.expecthim.com/2-kings-1.html'},
    13: {'name': '歷代志上',
         'link': 'https://www.expecthim.com/1-chronicles-1.html'},
    14: {'name': '歷代志下',
         'link': 'https://www.expecthim.com/2-chronicles-1.html'},
    15: {'name': '以斯拉記', 'link': 'https://www.expecthim.com/ezra-1.html'},
    16: {'name': '尼希米記', 'link': 'https://www.expecthim.com/nehemiah-1.html'},
    17: {'name': '以斯帖記', 'link': 'https://www.expecthim.com/esther-1.html'},
    18: {'name': '約伯記', 'link': 'https://www.expecthim.com/job-1.html'},
    19: {'name': '詩篇', 'link': 'https://www.expecthim.com/psalms-1.html'},
    20: {'name': '箴言', 'link': 'https://www.expecthim.com/proverbs-1.html'},
    21: {'name': '傳道書',
         'link': 'https://www.expecthim.com/ecclesiastes-1.html'},
    22: {'name': '雅歌',
         'link': 'https://www.expecthim.com/song-of-songs-1.html'},
    23: {'name': '以賽亞書', 'link': 'https://www.expecthim.com/isaiah-1.html'},
    24: {'name': '耶利米書', 'link': 'https://www.expecthim.com/jeremiah-1.html'},
    25: {'name': '耶利米哀歌',
         'link': 'https://www.expecthim.com/lamentations-1.html'},
    26: {'name': '以西結書', 'link': 'https://www.expecthim.com/ezekiel-1.html'},
    27: {'name': '但以理書', 'link': 'https://www.expecthim.com/daniel-1.html'},
    28: {'name': '何西阿書', 'link': 'https://www.expecthim.com/hosea-1.html'},
    29: {'name': '約珥書', 'link': 'https://www.expecthim.com/joel-1.html'},
    30: {'name': '阿摩司書', 'link': 'https://www.expecthim.com/amos-1.html'},
    31: {'name': '俄巴底亞書', 'link': 'https://www.expecthim.com/obadiah-1.html'},
    32: {'name': '約拿書', 'link': 'https://www.expecthim.com/jonah-1.html'},
    33: {'name': '彌迦書', 'link': 'https://www.expecthim.com/micah-1.html'},
    34: {'name': '那鴻書', 'link': 'https://www.expecthim.com/nahum-1.html'},
    35: {'name': '哈巴谷書', 'link': 'https://www.expecthim.com/habakkuk-1.html'},
    36: {'name': '西番雅書', 'link': 'https://www.expecthim.com/zephaniah-1.html'},
    37: {'name': '哈該書', 'link': 'https://www.expecthim.com/haggai-1.html'},
    38: {'name': '撒迦利亞書',
         'link': 'https://www.expecthim.com/zechariah-1.html'},
    39: {'name': '瑪拉基書', 'link': 'https://www.expecthim.com/malachi-1.html'},
    40: {'name': '馬太福音', 'link': 'https://www.expecthim.com/matthew-1.html'},
    41: {'name': '馬可福音', 'link': 'https://www.expecthim.com/mark-1.html'},
    42: {'name': '路加福音', 'link': 'https://www.expecthim.com/luke-1.html'},
    43: {'name': '約翰福音', 'link': 'https://www.expecthim.com/john-1.html'},
    44: {'name': '使徒行傳', 'link': 'https://www.expecthim.com/acts-1.html'},
    45: {'name': '羅馬書', 'link': 'https://www.expecthim.com/romans-1.html'},
    46: {'name': '哥林多前書',
         'link': 'https://www.expecthim.com/1-corinthians-1.html'},
    47: {'name': '哥林多後書',
         'link': 'https://www.expecthim.com/2-corinthians-1.html'},
    48: {'name': '加拉太書', 'link': 'https://www.expecthim.com/galatians-1.html'},
    49: {'name': '以弗所書', 'link': 'https://www.expecthim.com/ephesians-1.html'},
    50: {'name': '腓立比書',
         'link': 'https://www.expecthim.com/philippians-1.html'},
    51: {'name': '歌羅西書',
         'link': 'https://www.expecthim.com/colossians-1.html'},
    52: {'name': '帖撒羅尼迦前書',
         'link': 'https://www.expecthim.com/1-thessalonians-1.html'},
    53: {'name': '帖撒羅尼迦後書',
         'link': 'https://www.expecthim.com/2-thessalonians-1.html'},
    54: {'name': '提摩太前書',
         'link': 'https://www.expecthim.com/1-timothy-1.html'},
    55: {'name': '提摩太後書',
         'link': 'https://www.expecthim.com/2-timothy-1.html'},
    56: {'name': '提多書', 'link': 'https://www.expecthim.com/titus-1.html'},
    57: {'name': '腓利門書', 'link': 'https://www.expecthim.com/philemon-1.html'},
    58: {'name': '希伯來書', 'link': 'https://www.expecthim.com/hebrews-1.html'},
    59: {'name': '雅各書', 'link': 'https://www.expecthim.com/james-1.html'},
    60: {'name': '彼得前書', 'link': 'https://www.expecthim.com/1-peter-1.html'},
    61: {'name': '彼得後書', 'link': 'https://www.expecthim.com/2-peter-1.html'},
    62: {'name': '約翰一書', 'link': 'https://www.expecthim.com/1-john-1.html'},
    63: {'name': '約翰二書', 'link': 'https://www.expecthim.com/2-john-1.html'},
    64: {'name': '約翰三書', 'link': 'https://www.expecthim.com/3-john-1.html'},
    65: {'name': '猶大書', 'link': 'https://www.expecthim.com/jude-1.html'},
    66: {'name': '啟示錄', 'link': 'https://www.expecthim.com/revelation-1.html'}
}
